# Use a Mac build please
language: objective-c
osx_image: xcode9.3
rvm: 2.5.0 # Fastlane requires a version abopve 2.x

# Ensure that Fastlane, node and yarn are at the latest versions
before_install:
  - bundle update

# Let fastlane set up the other dependency managers
before_script:
- nvm install 8.4
- bundle exec fastlane setup

# Separate fastlane lanes so that they can be individually
# tested one by one during development
script:
- set +e # Workaround for Travis bug. See https://github.com/travis-ci/travis-ci/issues/6522
- bundle exec fastlane validate_env_vars
- bundle exec fastlane ci_deploy

notifications:
  slack:
    secure: NUWVxfrccR79maPv896T6vbUz89EH32zZw/ySoE5qpyu0sYGqtcQ9wUzrOOrt8rWNi49jocCKzfdv/A34q5emdbXByBfFsWoaKpznZ+I+IyCWyXvHBP4/wl4dmY/Q+Sv657gbSiEFwgqOyayXEtbTwfNUlR/+I1kMtRwibUKR35JkMJl+O7HeCaLDpDZA5YQfEljSIuhmvicdM5WObJemF0SRo1A3+7PrDCE54XM75H8vS6cOB527KJ6S7janQhHHA8yz51f0Uf57WIBne9X7C0TShmcvgHbYFYEWNWk5XSVolefsEasgzokl7edwguGIibf5SfuHAVuYf6an0F6bptsWIhUqgvWiF1Nfbbelfo9tWXVS3/YjqZUbaLxZ5ej4s7/ku6aLPfPnz+q3iPCZCPFf2ErLDQdXhhob+tPp+eX9sUip7Mpjh0s88crg/FaykIyOV2PhfOdsyIKNGW2ULdOAgxm72HdqHHSO/cBTsWR5WQOv0FnL+WbidLPybC2njosE/eFC/h14vB5hEeQ3dNTX0Kx38GXW/mFXcfbPYlOcbP+4rXWR6XWkkGnUaSQZQLvZC5qRF/z9jZhV8yYL8aprHtHH4QedM/so8604rbParrrli64K4sebKfzmnMzOHTlL2m7qLs7440OGYDzDqz0sOFeY2nZahm90B3zgCs=
env:
  global:
  - secure: gt/ZzonR7/ZRJOXj/CyKtUPH2rqbSOnlbC5rHHs+1HHKyRjql2G5mw7FYxpZSmwZXCoLUFFmGo7HecgHeR9yrRpEj/R+J1VhuRSSBGwNe2AhL0DvMQM1kEi2aEalv8ydsfrbDVfnY1wIiL9576uVGQAyvWrYbjnwhmKj86yvHzKGD4GCijZRXrovuN7QsKtVIAbSPe1vAmTv2v9JKrw0bRhA6nd3uQmSghOf9mYkDB241+p0Z9HZJ0Ked2K+1EkqoGfdLXzDuD2nH80niEUbHdybYUazQl3+aqETME/hBpf8qncvMG7Dc3IJih+qZYXJ/85yO1Q1rUu4q9jQFdZxRh7n2kXFwjv3/4maO1hoGFA9LNrsJQjfJQ9+qAzOMq/Kw9gs2IZKNAcMzoFrdt4coBmTTLyGWnx5UZKpEJLFd9yil++tcw/cEn6A6FMCieWS4hkLiD/XY8NDZ6LunpuXSdPk1bIrEgkRNujrLx5nzrmKWBWZfkX80LDLontCwD8UBdB/d7mK1hBoktx/6c9tac6lW2kMrk0E/p0a6SG2saf97tIlu1k0XW1pQEcvsLZBBA2JDaqqeqliX3H13cC4fdULwe7esWaOzvrRZHXY53MAmW2iDPo5X2rIpzlo4Cq9wMpCUKrdZnE8jDpS8BjKpKENUcwiib2PIk96ZzrNs+k=
  - secure: PUTPtnYR/Wgc8Jcvo/Y6DQd0bjG/f8n9r3YyZ6jmDIqYv+9yAQ2p5danc5i15ziUDDg6kdlG3ZCwuFRjmt8VLiARPo14Kmb/H97nc16eI0aSQxFkQfFrdlxR+t9cw29WTzBeK2ySLQ/wumwLdd3axGpAz4zRmM9YeVSTPCi+6ZgJbqcjkRW46ABQt4OUIpRgqXx/FZJYcuxooV63sNCwoRx7rSWmsIu/umOhQtzIXW1dBgE1s23+b4TKiS8k0GR3D7sQqpvpo7Ro8LVvJcvm8PJF/EJalLzzhsk6ivKS01Ct0CnCjH6y6uTwB2N7Zw7+XMkAT9JFIZtwE8RfXnQ1UgPukyUjW6Esy6iKTurmGz8t5PzkTy/X6F8ChsC3YCDjrfDBrSSL51Wvz32qC9rEqQd7clyvNMvQFTGNmblA/DboT4VEptvSMDARNtIn7hO5uXZhWMWhOw2VaZf+gnheR9RCpfI0FLKdyHU9PNxDv06w4m1+gQvjjbZ/QBsvUyZAchX7FdIfPErIDZ98RqmX96pIAwb8L/AYIx5BXbrrjB5F4eHVhQ47VexaRRAUxw3OlfMferO6UDDvnOLQ3xMNWy2vaYrCyxIspK2epoa36y9aWlqMiYVkCsuc43B4ggtjcyxlCnv6vXkVCCS6FjSR+UG89lLcjUG9Ahk6ryactiU=
