language: objective-c
osx_image: xcode8.2

before_install:
  - bundle update

before_script:
  - bundle exec fastlane setup

script:
  - bundle exec fastlane validate_env_vars
  - bundle exec fastlane stamp_plist

  - bundle exec fastlane ship
