language: objective-c
osx_image: xcode8.2

before_install:
  - bundle update

before_script:
  - git clone https://github.com/artsy/emission.git
  - cd emission && git checkout de-swift && npm install
  - git log -2
  - cd Example && pod repo update && pod install
  - cd ../..

script:
  - bundle exec fastlane validate_env_vars
  - bundle exec fastlane stamp_plist
  - bundle exec fastlane ship
